in_ch: 1
out_ch: 1
train_file: X_train_new.npy
test_file: X_test.npy
val_file: X_val.npy
gt_train_file: Y_train_new.npy
gt_val_file: Y_val.npy
out_dir: Results
lr: 0.001
beta1: 0.5
batchsize: 16
test_batchsize: 1
threads: 1
cuda: True
epoch: 1000
snapshot: 20
net_pretrained: Results/models/network_model_epoch_260.pth
net_pretrained_1: Ensemble/1network_model_epoch_100.pth
net_pretrained_2: Ensemble/2network_model_epoch_120.pth
net_pretrained_3: Ensemble/network_model_epoch_260.pth
net_pretrained_4: Ensemble/network_model_epoch_100.pth
net_pretrained_5: Ensemble/network_model_epoch_120.pth